app_demand:
    resource: "@AppBundle/Controller/DemandController.php"
    type:     annotation

ben_web_service:
    resource: "@BenWebServiceBundle/Resources/config/routing.yml"
    prefix:   /ws/v{version}
    defaults: { version: '1.0' }

app_commande:
    resource: "@AppBundle/Controller/CommandeController.php"
    type:     annotation

app_vente:
    resource: "@AppBundle/Controller/VenteController.php"
    type:     annotation
    
app_dashboard:
    resource: "@AppBundle/Controller/DashboardController.php"
    type:     annotation
    
ben_agro:
    resource: "@BenUserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# Route de FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /dashboard/notification
    
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications