<?php

namespace AppBundle\Entity;

/**
 * MeasureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureRepository extends \Doctrine\ORM\EntityRepository {

    public function getMeasures($id) {
//        $query = $this->createQueryBuilder('m')
//                ->innerJoin('m.products', 'p', 'WITH', 'p.name = :product')
//                ->setParameter('product', $product)

$query = $this->createQueryBuilder('m')
        ->join('m.products', 'p')
        ->addSelect('p')
        ->where('p.id = :id');
 
$measures = $query->getTasks(); // pas de nouvelle requête déclenché
/*
                ->getQuery()
                ->getArrayResult();

        return $query;*/
    }

}
