<?php

namespace AppBundle\Entity;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
      public function getDashboardCountMarket($user) {
        return $this->createQueryBuilder('o')
                        ->select('COUNT(o)')
                        ->where('o.user  =:user')
                        ->andwhere('o.deleted  =:deleted')
                        ->andwhere('o.canceled  =:canceled')
                        ->setParameter('user', $user)
                        ->setParameter('deleted', false)
                        ->setParameter('canceled', false)
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
