<?php

namespace AppBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMeasures($id) {
        $query = $this->createQueryBuilder('p')
            ->join('p.measures', 'm')
            ->addSelect('m')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getArrayResult();
        return $query;
    }   
}
