<?php

namespace AppBundle\Entity;

/**
 * SupplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplyRepository extends \Doctrine\ORM\EntityRepository
{
      public function getDashboardCountMarket($user) {
        return $this->createQueryBuilder('s')
                        ->select('COUNT(s)')
                        ->where('s.user  =:user')
                        ->andwhere('s.deleted  =:deleted')
                        ->andwhere('s.canceled  =:canceled')
                        ->setParameter('user', $user)
                        ->setParameter('deleted', false)
                        ->setParameter('canceled', false)
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
